(ns
 gilded-gauge.rankings
 "Autogenerated namespace (see scripts/scrape.clj)")
(def
 rankings
 [["Jeff Bezos"
   189.0
   "thumb/6/6c/Jeff_Bezos_at_Amazon_Spheres_Grand_Opening_in_Seattle_-_2018_%2839074799225%29_%28cropped%29.jpg/220px-Jeff_Bezos_at_Amazon_Spheres_Grand_Opening_in_Seattle_-_2018_%2839074799225%29_%28cropped%29.jpg"]
  ["Bill Gates"
   124.0
   "thumb/a/a0/Bill_Gates_2018.jpg/220px-Bill_Gates_2018.jpg"]
  ["Elon Musk"
   103.0
   "thumb/e/ed/Elon_Musk_Royal_Society.jpg/220px-Elon_Musk_Royal_Society.jpg"]
  ["Mark Zuckerberg"
   100.0
   "thumb/1/18/Mark_Zuckerberg_F8_2019_Keynote_%2832830578717%29_%28cropped%29.jpg/220px-Mark_Zuckerberg_F8_2019_Keynote_%2832830578717%29_%28cropped%29.jpg"]
  ["Bernard Arnault"
   86.4
   "thumb/d/de/Bernard_Arnault_%283%29_-_2017_%28cropped%29.jpg/220px-Bernard_Arnault_%283%29_-_2017_%28cropped%29.jpg"]
  ["Mukesh Ambani"
   85.3
   "thumb/6/69/Mukesh_Ambani.jpg/220px-Mukesh_Ambani.jpg"]
  ["Warren Buffett"
   80.4
   "thumb/5/51/Warren_Buffett_KU_Visit.jpg/220px-Warren_Buffett_KU_Visit.jpg"]
  ["Steve Ballmer"
   75.8
   "thumb/4/44/Steve_Ballmer_2014.jpg/220px-Steve_Ballmer_2014.jpg"]
  ["Larry Page"
   71.3
   "thumb/e/ec/Larry_Page_in_the_European_Parliament%2C_17.06.2009_%28cropped%29.jpg/220px-Larry_Page_in_the_European_Parliament%2C_17.06.2009_%28cropped%29.jpg"]
  ["Larry Ellison"
   70.3
   "thumb/0/00/Larry_Ellison_picture.png/220px-Larry_Ellison_picture.png"]
  ["Sergey Brin"
   69.1
   "thumb/a/a2/Sergey_Brin_cropped.jpg/220px-Sergey_Brin_cropped.jpg"]
  ["Francoise Bettencourt Meyers" 66.2]
  ["Rob Walton" 62.2]
  ["Jim Walton"
   62.0
   "thumb/b/bb/Jim_Walton_attends_shareholders_meeting.jpg/220px-Jim_Walton_attends_shareholders_meeting.jpg"]
  ["MacKenzie Scott" 61.5]
  ["Alice Walton"
   61.4
   "thumb/e/e1/Alice_Walton_%28cropped%29.jpg/220px-Alice_Walton_%28cropped%29.jpg"]
  ["Amancio Ortega"
   60.4
   "thumb/5/59/Amancio_Ortega_Portrait_Painting_Collage_By_Danor_Shtruzman.jpg/220px-Amancio_Ortega_Portrait_Painting_Collage_By_Danor_Shtruzman.jpg"]
  ["Jack Ma"
   58.4
   "thumb/a/a9/Enabling_eCommerce-_Small_Enterprises%2C_Global_Players_%2839008130265%29_%28cropped%29.jpg/220px-Enabling_eCommerce-_Small_Enterprises%2C_Global_Players_%2839008130265%29_%28cropped%29.jpg"]
  ["Julia Flesher Koch" 55.9]
  ["Charles Koch"
   55.9
   "thumb/2/20/Charles_Koch_portrait_%28cropped%29.jpg/220px-Charles_Koch_portrait_%28cropped%29.jpg"]
  ["Michael Bloomberg"
   54.9
   "thumb/e/e2/Mike_Bloomberg_Headshot.jpg/220px-Mike_Bloomberg_Headshot.jpg"]
  ["Zhong Shanshan" 53.4]
  ["Pony Ma" 52.7 "thumb/d/d9/Pony_Ma_2011.jpg/220px-Pony_Ma_2011.jpg"]
  ["Carlos Slim"
   46.9
   "thumb/b/bf/Carlos_Slim_%2845680472234%29_%28cropped%29.jpg/220px-Carlos_Slim_%2845680472234%29_%28cropped%29.jpg"]
  ["Phil Knight"
   44.4
   "thumb/b/bc/Philknightfootball.jpg/200px-Philknightfootball.jpg"]
  ["Francois Pinault"
   44.3
   "thumb/4/48/Fran%C3%A7ois_Pinault_Stade_rennais_-_Le_Havre_AC_20150708_44.jpg/220px-Fran%C3%A7ois_Pinault_Stade_rennais_-_Le_Havre_AC_20150708_44.jpg"]
  ["John Mars" 42.0]
  ["Jacqueline Mars"
   42.0
   "thumb/5/5c/Jacqueline_Mars_Portrait_Painting_Collage_By_Danor_Shtruzman.jpg/220px-Jacqueline_Mars_Portrait_Painting_Collage_By_Danor_Shtruzman.jpg"]
  ["Michael Dell"
   37.5
   "thumb/c/ce/Michael_Dell_2010.jpg/220px-Michael_Dell_2010.jpg"]
  ["Dan Gilbert"
   35.6
   "thumb/b/b6/Dan_Gilbert_Chairman_of_Quicken_Loans_and_Majority_Owner_of_the_Cleveland_Cavaliers.jpg/220px-Dan_Gilbert_Chairman_of_Quicken_Loans_and_Majority_Owner_of_the_Cleveland_Cavaliers.jpg"]
  ["Giovanni Ferrero" 33.1]
  ["Gerard Wertheimer" 32.8]
  ["Alain Wertheimer" 32.8]
  ["Len Blavatnik"
   32.4
   "thumb/e/ea/Leonard_Blavatnik%2C_February_2018_%284568%29_%28cropped%29.jpg/220px-Leonard_Blavatnik%2C_February_2018_%284568%29_%28cropped%29.jpg"]
  ["Tadashi Yanai"
   32.4
   "thumb/1/10/Tadashi_Yanai.jpg/220px-Tadashi_Yanai.jpg"]
  ["Laurene Powell Jobs"
   32.3
   "thumb/9/97/Laurene_Powell_Jobs.jpg/220px-Laurene_Powell_Jobs.jpg"]
  ["Li Ka-Shing"
   31.8
   "thumb/e/e8/Li_Ka_Shing.jpg/220px-Li_Ka_Shing.jpg"]
  ["Abby  Johnson" 31.1]
  ["Hui Ka Yan" 29.6]
  ["William Ding" 28.7]
  ["Sheldon Adelson"
   28.4
   "thumb/f/f9/Sheldon_Adelson_crop.jpg/220px-Sheldon_Adelson_crop.jpg"]
  ["He Xiangjian" 28.3]
  ["Yang Huiyan" 26.8]
  ["Takemitsu Takizaki" 26.4]
  ["Goh Cheng Liang" 25.9]
  ["Vladimir Potanin" 25.4 "7/7d/Vladimir_Potanin.jpg"]
  ["Colin Huang" 25.4]
  ["Eric Yuan" 24.4]
  ["Pang Kang" 24.2]
  ["Leonard  Lauder" 24.0]])
