name: gild

on:
  schedule:
    - cron: '0 23 * * 1-5'
  workflow_dispatch:

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.5
      - run: |
          cd $GITHUB_WORKSPACE
          ./scripts/get-rankings.sh
          git config --global user.email "dan@oxism.com"
          git config --global user.name "Dan Motzenbecker"
          git add src/gilded_gauge/rankings.cljs
          git commit -m 'update ranking'
          git push origin master
          npx distilla
