name: gild

on:
  schedule:
    - cron: '0 4 * * 2-6'
  workflow_dispatch:

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          lein: 2.11.3
      - name: setup
        run: |
          cd $GITHUB_WORKSPACE
          lein deps
      - name: fetch
        run: ./scripts/get-rankings.sh
      - name: commit
        run: |
          if [[ `git status --porcelain --untracked-files=no` ]]; then
            git config --global user.email "dan@oxism.com"
            git config --global user.name "Dan Motzenbecker"
            git add src/gilded_gauge/rankings.cljs
            git commit -m 'update ranking'
            git push origin master
            npx distilla
          fi
